SERVO_MIN = 600
SERVO_MAX = 2400
SERVO_NEUTRAL = 1500

OUTPINS_BCM = [7,8,10,11,14,15,18,23]
INPINS_BCM = [9]

LIGHT_OUT_BCM = 14
SOUND_OUT_BCM = 15

CLAW_OUT_BCM = 7
WRIST_OUT_BCM = 18
ELBOW_OUT_BCM = 23

SPICS = 8
SPIMISO = 9
SPIMOSI = 10
SPICLK = 11

INIT_CLAW_POSITION = SERVO_NEUTRAL
INIT_WRIST_POSITION = SERVO_NEUTRAL
INIT_ELBOW_POSITION = SERVO_NEUTRAL

HEAT_THRESH = 200
TOUCH_THRESH = 25
MUSCLE_FACTOR = 150 

SAMPLE_FREQUENCY = 2000 #Hz
SAMPLE_WINDOW = 0.03 #seconds
SAMPLE_NUMBER = SAMPLE_FREQUENCY * SAMPLE_WINDOW
SAMPLE_PERIOD = 1/SAMPLE_FREQUENCY 

ANALOG_CLAW_IN = [0,1]
ANALOG_WRIST_IN = [2,3]
ANALOG_ELBOW_IN = [4,5]
ANALOG_TEMP_IN = 6
ANALOG_TOUCH_IN = 7

ROUND = 2

TEST = 1
